#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Oct 31 22:02:43 2024

@author: sofiyapatra
"""

s = 'GATTAGGGAAGGATCCTGAAGTTTTGGTGCACAAGGGCTCCAGTCGTAAAAGCCCCTTTCAGAACCCTTCCCGGGGTGGCGACCCTCAGCCACGGCAATGTATACCCATCAGTACTCTGCGCATCGATCCGATAGACAGGGTCAGTACTAACCGTTATTGTGTCGTATAAATACCATCCTATGTCCCCTTCATTATGCGTCGGACTGGCGAGCACCCGCTTTACCACCTAATCCAGTGATCGGTGGGTGAGCACAAGTTGTTTCAGCTATCATAGTTGGGCGCTGAGGCGCCGACATCATTTTGAAGTACTAACGCCAGCCCAAAATGATCAATGGTGCAGGCAGAGCGCAGCCTTGTACTTTTTGGACCCGATTTATTGGTTGAATGTGTTCAATCTCCAAGCGGGTCAGCCCGGCAAGGATGATCACAATATCTTTTTCGACATATAGAAGAGTAACTTCCAAGACTGGAGGCAGTTTTAGGTATAGTGGTATAATTGAAATGCGTTGTGGAAGTCGAATGTATCCCCCCGGTAGCCAAACCGAACCATCCCCCCTGCGAACCTGTATCTGGACTGAGAACGACACAGGAATCTAGGGCCAGTCCACTTTTCTTAAATTCTCAGACTGGGTCTCTGGATTGTTGGGCGCGAGTACCCGACGGCGGGCTGATACACTTAGGGAGTTATTCGAACGTACGTGCGCTAATGCGTAAGTACTAATTTCCGTCGTTAATAATGTTGGCGGGTCTTACACGTCTTGGCGATCACCATCTAGGGAATAGGCCTTACTAATGTTGTCGCTTGTGCGACATCGGCTGTAATCTTTCTAGGTCCTGCGATTATACTCACCTCGCTCGGTAACAGCTCCCAAAACTGGGGAGCCATCACCGAAAAACGAACATTTATTCGTT'

s.count('A')

def counter(string):
    list = [s.count('A'), s.count('T'), s.count('C'), s.count('G')]
    return list

def counter2(string):
    count = []
    for nt in 'ACGT' :
        count.append(string.count(nt))
    print(*count)

