#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Nov  2 16:37:54 2024

@author: sofiyapatra

Problem
In DNA strings, symbols 'A' and 'T' are complements of each other, as are 'C' and 'G'.

The reverse complement of a DNA string s
 is the string sc
 formed by reversing the symbols of s
, then taking the complement of each symbol (e.g., the reverse complement of "GTCA" is "TGAC").

Given: A DNA string s
 of length at most 1000 bp.

Return: The reverse complement sc
 of s
.
"""

#longway
def revcomplement(string):
    #reverse string
    rev = string[::-1]
    rcomp = ''
    #create complement string
    for nt in rev:
        if nt == 'A':
            rcomp += 'T'
        elif nt == 'C':
            rcomp += 'G'
        elif nt == 'G':
            rcomp += 'C'
        elif nt == 'T':
            rcomp += 'A'
    return rcomp

revcomplement("CATACATGGCAGAGCGACAGTAGTGGAGCCTGGTGCGGCCTGGAATTCGGGGGCGTATTTGAGGAGTCGCTGGCCAATTCGTGCCTGATTCGTTCAAAGCAAGCGCTGGTTGGTAAGGGAATCGCTTGACTGGCTAAGGAATTGATGGTTGAATTCCAGTCTACGGCGGCCGGTATTCTGGCAACCACGAGACATCAATTTGCCGGCGTTGGCTTGTGCTCCCGACGCATGCGTAATGGGAGTTAGAGTCCTAGAAGAGGGATGCATCCATAAATGTCCGTCAATCAACAGGGGAGCCCCTATCGATCTTAAGCCTGGAGTACGCCCCGCACTCACCAACTATTATTTCTCTGTACTGCGGACCAATCACGATTAGTGGAAAAGGAATCTCGGAACGGAGCTGCCTGAGGTAGCAATTGATAACGCGACGAATCGACCGGGGGTGATCTAGTGTGCACGACGGATCGCCTGGGACCCTAATCTACCCGAACAGTGGGTCGTGTAACTGAAAACTCAGGAGCCCTATGCTTCGGATAGTACGACTTTAAGGACTATCAATATGGCCAAGCTTGGCACTTTGCGTTTACTTCCTATCATCATTACAAATATCCAAGCCAATTGAACGTCCCGTATACGGATACAATCTCATGGTTCTGTCTGAGTAATATGGCGTATTACCTTAGACCGGTAGAGGCGTGTAGCCCAGCGGTGCCACGTCCGTAAATTTATCCACTTCAGGGGGTGCTTTACTTACCACATGACGGGTTCTTCCATAAGTTGACCTCCTCTGTCAGTAGTGTGTTGCCAAGTGGTTTTGCAAATGTGGTAGGACCCGGAGTATGAGGTCCCCCAACATTAATAAACCACT")

#better way!
def revcomplement2(string):
    #reverse string
    rev = string[::-1]
    code = {'C':'G',
            'G':'C',
            'A':'T',
            'T':'A'}
    rcomp = ''
    #create complement string
    for nt in rev: 
        rcomp += code[nt]
    return rcomp


revcomplement2("CATACATGGCAGAGCGACAGTAGTGGAGCCTGGTGCGGCCTGGAATTCGGGGGCGTATTTGAGGAGTCGCTGGCCAATTCGTGCCTGATTCGTTCAAAGCAAGCGCTGGTTGGTAAGGGAATCGCTTGACTGGCTAAGGAATTGATGGTTGAATTCCAGTCTACGGCGGCCGGTATTCTGGCAACCACGAGACATCAATTTGCCGGCGTTGGCTTGTGCTCCCGACGCATGCGTAATGGGAGTTAGAGTCCTAGAAGAGGGATGCATCCATAAATGTCCGTCAATCAACAGGGGAGCCCCTATCGATCTTAAGCCTGGAGTACGCCCCGCACTCACCAACTATTATTTCTCTGTACTGCGGACCAATCACGATTAGTGGAAAAGGAATCTCGGAACGGAGCTGCCTGAGGTAGCAATTGATAACGCGACGAATCGACCGGGGGTGATCTAGTGTGCACGACGGATCGCCTGGGACCCTAATCTACCCGAACAGTGGGTCGTGTAACTGAAAACTCAGGAGCCCTATGCTTCGGATAGTACGACTTTAAGGACTATCAATATGGCCAAGCTTGGCACTTTGCGTTTACTTCCTATCATCATTACAAATATCCAAGCCAATTGAACGTCCCGTATACGGATACAATCTCATGGTTCTGTCTGAGTAATATGGCGTATTACCTTAGACCGGTAGAGGCGTGTAGCCCAGCGGTGCCACGTCCGTAAATTTATCCACTTCAGGGGGTGCTTTACTTACCACATGACGGGTTCTTCCATAAGTTGACCTCCTCTGTCAGTAGTGTGTTGCCAAGTGGTTTTGCAAATGTGGTAGGACCCGGAGTATGAGGTCCCCCAACATTAATAAACCACT")