#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Oct 31 22:38:19 2024

@author: sofiyapatra

Problem
An RNA string is a string formed from the alphabet containing 'A', 'C', 'G', and 'U'.

Given a DNA string t
 corresponding to a coding strand, its transcribed RNA string u
 is formed by replacing all occurrences of 'T' in t
 with 'U' in u
.

Given: A DNA string t
 having length at most 1000 nt.

Return: The transcribed RNA string of t
.
"""

DNA = 'TTTCTGTATCTTTATTTATTAGCCAATTGGTATGCAAAGAACTTGAATCAGCAATTTTTTTAGCTAACCCGCTATGCGCTCGGTTATTGTCTTGGAATAGTGGGACGGTGCGGTTGGGCGGAAGTGTTTTAATACAAATATGAAGAATGTTTGCCCTCGGGAGGCACCAACAAGGTTCTCAGGCATTGACAGAGTAAATGACCGATCTAATAATCTACAAAGCGGGTTGATGTATACCCTTCACATTCTACGAATAAGAGGAGAGAGTTTTCCGATTCTACATATAATTCGGAAACTGTGGGCCATGAGAGGGTATACGCTATTAATTTTCCCACTTGGCCGACTCCTTCTAATTAGCGATTTCAGCCAATACTGTGCACTATCTCCTCTCCCCGTTATAATATACTCTTATAAGATAGACAGTGTGCTACGTGGGACTTCAGGAAGCTCTTAGCACGGTCTGTCCTTCAAATCGAACGGAGGTGATCTTTCAACAAGATGACAACGAGTTTATTGTATGTGGTCCTGATACGGATAATCTCAAGCATGCTACACAGCGGAAACAGTCTAACTATAGTAACAAACCTCAAGGAGAAGGATTTCCAACAGTTGGTTATTGTGGCCTGGGCCCTCAGCCAGACCCTGAATGGTTCTGAACAAGATGTAACTTGTACTCCGTTTATTGCGGAGTCTGACATTACTAATTTCTTTCAGTCCAGAGAGAAAAAACGCCTCAAGTGTAGAATGGTCGTTGCCCCCTGGGACCCCACGCGTTAACGATCGCTATGCACGTATTGGTTGCGTCCCAGCTTTATACTTCGGCTGCCGTCCCCATCGCAGCTTCGAGTAATCTACCCCGGCGGCACCGGGCACTCGCTTCGTCAATCAGTGCACAAAAGTGCGGTA'

def transcription(s): 
    RNA = s.replace('T', 'U')
    return(RNA)

transcription(DNA)